### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by hamish** [Douile/rust-build.action#1]
Hi, 

I love the idea of the rust release binary action. I'm trying to build a very simple rust project with the action, but I'm getting errors during the build. An example is here:
https://github.com/hamish/rust-play/actions/runs/260597983

I get 3 warnings saying that 'CMD_PATH not set' and then an error saying that "The job was canceled because 'x86_64-unknown-linux-gnu" failed.'

Do I need to set CMD_PATH in the env tag? If so what would be a suitable value?
Do you have a simple project using the action that I can copy?

Thanks.

**Comment by Douile** [comment]
This project is currently a WIP, I haven't got it working fully yet. With my own project I have problems with openssl. If you change version from 0.1.1 to 0.1.4 (0.1.5 is broken) you might get lucky (if you don't use the `openssl-sys` package). You do not need to set CMD_PATH it is an artifact from the [go-build](https://github.com/ngs/go-release.action) I based this on.

[Example action](https://github.com/Douile/discord-enumerator/blob/3832d4886497b84b2148b20d32a4164fd31bb062/.github/workflows/release.yml)

**Comment by Douile** [comment]
@hamish 
I have performed the first successful compilation with this action using this [config](https://github.com/Douile/discord-enumerator/blob/ed2c7ad9ad04fe41e169abc7ebe3c2f76072b97a/.github/workflows/release.yml).

The problem was I was using alpine (due to smaller image size) but alpine doesn't have glibc which I believe was causing gnu builds to fail. I will attempt to convert the action to debain based.
